SSLProxyEngine On

SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off

ProxyPreserveHost On

# ==========================================================
# API
# ==========================================================
ProxyPass /api https://spring-app:8443/api
ProxyPassReverse /api https://spring-app:8443/api

# ==========================================================
# Swagger
# ==========================================================
ProxyPass /v3 https://spring-app:8443/v3
ProxyPassReverse /v3 https://spring-app:8443/v3

ProxyPass /swagger-ui https://spring-app:8443/swagger-ui
ProxyPassReverse /swagger-ui https://spring-app:8443/swagger-ui

# ==========================================================
# WebSocket
# ==========================================================
ProxyPass /ws https://spring-app:8443/ws
ProxyPassReverse /ws https://spring-app:8443/ws

# ==========================================================
# FRONTEND - MUST BE LAST
# ==========================================================
ProxyPass / http://maw3idi-frontend:80/
ProxyPassReverse / http://maw3idi-frontend:80/
